//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdBoard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public Ad()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Text { get; set; }
        public bool IsPublic { get; set; }
        public int AdTypeId { get; set; }
        public int UserId { get; set; }
    
        public virtual AdType AdType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Image> Images { get; set; }
    }
}
