//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdBoard
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Ads = new HashSet<Ad>();
        }
    
        public int Id { get; set; }
        public System.DateTime RegDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public string Cookies { get; set; }
        public string Password { get; set; }
        public bool IsBlock { get; set; }
        public int RoleId { get; set; }
    
        public virtual ICollection<Ad> Ads { get; set; }
        public virtual Role Role { get; set; }
    }
}
